apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: lumen-prometheus
    url: http://lumen-monitoring-prometheus:9090
    access: proxy
    isDefault: true
    editable: false
